### ISSUE TITLE
Compress data contents when exporting MFFs into JSON files

### ISSUE THREAD

**Issue by damian5710** [BEL-Public/mffpy#17]
OS/Platform: All

Enhancement Request:

We should compress data contents when exporting MFFs into JSON files.

Acceptance Criteria:

- Data contents stored in the exported JSON files are compressed (e.g. using base64 encoding scheme).

**Comment by ViridianForge** [comment]
Adding in a user experience for this enhancement.
Users of BELCO's EMFAV product just reported trying to load in an MFF that has been segmented and then converted into JSON results in a file too large for EMFAV to handle.

For the purview of MFFpy - this feature's implementation could help that.

**Comment by damian5710** [comment]
We now compress the EEG data before exporting MFF contents into JSON format. 

If we don't need to compress any other content, I think we can close this Issue. What do you think @ViridianForge and @ephathaway ?

**Comment by ViridianForge** [comment]
I agree. If we were to need to compress other content in the future, or change our compression output for JSON - we can open a new enhancement.  Thank you for your contribution @damian5710!
