### ISSUE TITLE
Time units of epoch offset

### ISSUE THREAD

**Issue by ephathaway** [BEL-Public/mffpy#5]
The function `add_block` in `mffpy/bin_writer.py` has a `offset_us` argument that can be given if you want there to be a break between blocks. The documentation says this is given in milliseconds, but I think it needs to be given in microseconds currently. For example, if I want to have a 1 second break between blocks, I would have to specify 1000000 (microseconds) for the offset instead of 1000 (milliseconds).

**Comment by ViridianForge** [comment]
Closing as addressed by PR #9 - thanks for the keen eye @ephathaway !
