### ISSUE TITLE
README says that 'make test' runs tests but project doesn't contain any makefiles

### ISSUE THREAD

**Issue by yurivict** [BEL-Public/mffpy#75]

**Comment by GeorgeHernandez541** [comment]
Hello @yurivict,
The develop branch shows there is one [makefile](https://github.com/BEL-Public/mffpy/blob/develop/makefile) with three targets currently present. 
I did notice that `mypy` will stop the tests from running if it reports any errors.

**Comment by GeorgeHernandez541** [comment]
@yurivict, could you clarify the issue you are facing?

**Comment by GeorgeHernandez541** [comment]
@yurivict, please feel free to open the issue again if the problem persists.
